# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=120)),
                ('segment', models.TextField()),
                ('cikistarihi', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=120)),
                ('segment', models.TextField()),
                ('cikistarihi', models.DateTimeField()),
            ],
        ),
    ]
